---
- name: download ping_exporter
  copy:
    src: "{{ tarball_ping_exporter }}"
    dest: "{{ tmp_ping_exporter }}"
- name: create ping_exporter group
  group:
    name: ping_exporter
    system: yes
- name: create ping_exporter user
  user:
    name: ping_exporter
    create_home: no
    shell: /sbin/nologin
    group: ping_exporter
    system: yes
- name: create ping_exporter directories
  file:
    name: "{{ item }}"
    state: directory
    owner: ping_exporter
    group: ping_exporter
  with_items:
    - /opt/ping_exporter
    - /etc/ping_exporter
- name: install ping_exporter
  unarchive:
    dest: /opt/ping_exporter
    owner: ping_exporter
    group: ping_exporter
    remote_src: yes
    src: "{{ tmp_ping_exporter }}"
    extra_opts: ["--strip=2"]
- name: configure ping_exporter
  copy:
    src: files/etc/ping_exporter/config.yml
    dest: /etc/ping_exporter/config.yml
    force: "{{ overwrite_configs }}"
- name: copy ping_exporter service unit
  copy:
    src: files/etc/systemd/system/ping_exporter.service
    dest: /etc/systemd/system/ping_exporter.service
    force: "{{ overwrite_services }}"
