---
- name: create ping_exporter directories
  file:
    name: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
    - /opt/ping_exporter
    - /etc/ping_exporter
- name: install ping_exporter
  unarchive:
    dest: /opt/ping_exporter
    owner: root
    group: root
    remote_src: no
    src: "{{ tarball_ping_exporter }}"
    extra_opts: ["--strip=2"]
- name: configure ping_exporter
  copy:
    src: files/etc/ping_exporter/config.yml
    dest: /etc/ping_exporter/config.yml
    force: "{{ overwrite_configs }}"
- name: copy ping_exporter service unit
  copy:
    src: files/etc/systemd/system/ping_exporter.service
    dest: /etc/systemd/system/ping_exporter.service
    force: "{{ overwrite_services }}"
- name: write ping_exporter version
  shell: "echo \"{{ ping_exporter_version }}\" > /opt/ping_exporter/version"
