---
- name: create /opt/node_exporter
  file:
    name: /opt/node_exporter
    state: directory
    owner: root
    group: root
- name: install node_exporter
  unarchive:
    dest: /opt/node_exporter
    owner: root
    group: root
    remote_src: yes
    src: "{{ url_node_exporter }}"
    extra_opts: ["--strip=1"]
- name: copy node_exporter service unit
  copy:
    src: files/etc/systemd/system/node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    force: "{{ overwrite_services }}"
- name: write node_exporter version
  shell: "echo \"{{ node_exporter_version }}\" > /opt/node_exporter/version"
