---
- name: create node_exporter group
  group:
    name: node_exporter
    system: yes
- name: create node_exporter user
  user:
    name: node_exporter
    create_home: no
    shell: /sbin/nologin
    group: node_exporter
    system: yes
- name: create /opt/node_exporter
  file:
    name: /opt/node_exporter
    state: directory
    owner: node_exporter
    group: node_exporter
- name: install node_exporter
  unarchive:
    dest: /opt/node_exporter
    owner: node_exporter
    group: node_exporter
    remote_src: yes
    src: "{{ url_node_exporter }}"
    extra_opts: ["--strip=1"]
- name: copy node_exporter service unit
  copy:
    src: files/etc/systemd/system/node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    force: "{{ overwrite_services }}"
