---
- name: load architecture-dependent configuration
  include_vars:
    file: "vars/config_{{ ansible_architecture }}.yaml"

- import_tasks: get-versions.yml
- import_tasks: stop-services.yml
- import_tasks: install-node-exporter.yml
  when: install_node_exporter
- import_tasks: install-ping-exporter.yml
  when: install_ping_exporter
- import_tasks: install-prometheus.yml
  when: install_prometheus
- import_tasks: start-services.yml
- import_tasks: cleanup.yml
