---
- name: restart prometheus
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: prometheus
  when: install_prometheus
- name: restart node_exporter
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: node_exporter
  when: install_node_exporter
- name: restart ping_exporter
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: ping_exporter
  when: install_ping_exporter
